export const keys = {
    en: [
        ['~ `', 'Backquote'],
        ['! 1', 'Digit1'],
        ['@ 2', 'Digit2'],
        ['# 3', 'Digit3'],
        ['$ 4', 'Digit4'],
        ['% 5', 'Digit5'],
        ['^ 6', 'Digit6'],
        ['& 7', 'Digit7'],
        ['* 8', 'Digit8'],
        ['( 9', 'Digit9'],
        [') 0', 'Digit0'],
        ['_ -', 'Minus'],
        ['+ =', 'Equal'],
        ['Backspace', 'Backspace'],
        //~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
        ['Tab', 'Tab'],
        ['Q', 'KeyQ'],
        ['W', 'KeyW'],
        ['E', 'KeyE'],
        ['R', 'KeyR'],
        ['T', 'KeyT'],
        ['Y', 'KeyY'],
        ['U', 'KeyU'],
        ['I', 'KeyI'],
        ['O', 'KeyO'],
        ['P', 'KeyP'],
        ['{ [', 'BracketLeft'],
        ['} ]', 'BracketRight'],
        ['| \\', 'Backslash'],
        ['Del', 'Delete'],
        //~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
        ['Caps\tLock', 'CapsLock'],
        ['A', 'KeyA'],
        ['S', 'KeyS'],
        ['D', 'KeyD'],
        ['F', 'KeyF'],
        ['G', 'KeyG'],
        ['H', 'KeyH'],
        ['J', 'KeyJ'],
        ['K', 'KeyK'],
        ['L', 'KeyL'],
        [': ;', 'Semicolon'],
        ['" \'', 'Quote'],
        ['Enter', 'Enter'],
        //~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
        ['Shift', 'ShiftLeft'],
        ['\\', 'Backslash'],
        ['Z', 'KeyZ'],
        ['X', 'KeyX'],
        ['C', 'KeyC'],
        ['V', 'KeyV'],
        ['B', 'KeyB'],
        ['N', 'KeyN'],
        ['M', 'KeyM'],
        ['< ,', 'Comma'],
        ['> .', 'Period'],
        ['? /', 'Slash'],
        ['Up', 'ArrowUp'],
        ['Shift', 'ShiftRight'],
        //~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
        ['Ctrl', 'ControlLeft'],
        ['Win', 'MetaLeft'],
        ['Alt', 'AltLeft'],
        ['', 'Space'],
        ['Alt', 'AltRight'],
        ['Ctrl', 'ControlRight'],
        ['Left', 'ArrowLeft'],
        ['Down', 'ArrowDown'],
        ['Right', 'ArrowRight'],
        

    ],
    ru: []
};