export const keys = {
    en: [
        ['~ `', 'Backquote'],
        ['! 1', 'Digit1'],
        ['@ 2', 'Digit2'],
        ['# 3', 'Digit3'],
        ['$ 4', 'Digit4'],
        ['% 5', 'Digit5'],
        ['^ 6', 'Digit6'],
        ['& 7', 'Digit7'],
        ['* 8', 'Digit8'],
        ['( 9', 'Digit9'],
        [') 0', 'Digit0'],
        ['_ -', 'Minus'],
        ['+ =', 'Equal'],
        ['Backspace', 'Backspace', '_func'],
        //~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
        ['Tab', 'Tab', '_func'],
        ['Q', 'KeyQ'],
        ['W', 'KeyW'],
        ['E', 'KeyE'],
        ['R', 'KeyR'],
        ['T', 'KeyT'],
        ['Y', 'KeyY'],
        ['U', 'KeyU'],
        ['I', 'KeyI'],
        ['O', 'KeyO'],
        ['P', 'KeyP'],
        ['{ [', 'BracketLeft'],
        ['} ]', 'BracketRight'],
        ['| \\', 'Backslash'],
        ['Del', 'Delete'],
        //~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
        ['Caps\tLock', 'CapsLock', '_func'],
        ['A', 'KeyA'],
        ['S', 'KeyS'],
        ['D', 'KeyD'],
        ['F', 'KeyF'],
        ['G', 'KeyG'],
        ['H', 'KeyH'],
        ['J', 'KeyJ'],
        ['K', 'KeyK'],
        ['L', 'KeyL'],
        [': ;', 'Semicolon'],
        ['" \'', 'Quote'],
        ['Enter', 'Enter', '_func'],
        //~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
        ['Shift', 'ShiftLeft', '_func'],
        ['\\', 'Backslash'],
        ['Z', 'KeyZ'],
        ['X', 'KeyX'],
        ['C', 'KeyC'],
        ['V', 'KeyV'],
        ['B', 'KeyB'],
        ['N', 'KeyN'],
        ['M', 'KeyM'],
        ['< ,', 'Comma'],
        ['> .', 'Period'],
        ['? /', 'Slash'],
        ['', 'ArrowUp', '_func'],
        ['Shift', 'ShiftRight', '_func'],
        //~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
        ['Ctrl', 'ControlLeft', '_func'],
        ['Win', 'MetaLeft', '_func'],
        ['Alt', 'AltLeft', '_func'],
        ['', 'Space'],
        ['Alt', 'AltRight', '_func'],
        ['Ctrl', 'ControlRight', '_func'],
        ['', 'ArrowLeft', '_func'],
        ['', 'ArrowDown', '_func'],
        ['', 'ArrowRight', '_func'],
        

    ],
    ru: [
        ['Ё', 'Backquote'],
        ['! 1', 'Digit1'],
        ['" 2', 'Digit2'],
        ['№ 3', 'Digit3'],
        ['; 4', 'Digit4'],
        ['% 5', 'Digit5'],
        [': 6', 'Digit6'],
        ['? 7', 'Digit7'],
        ['* 8', 'Digit8'],
        ['( 9', 'Digit9'],
        [') 0', 'Digit0'],
        ['_ -', 'Minus'],
        ['+ =', 'Equal'],
        ['Backspace', 'Backspace', '_func'],
        //~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
        ['Tab', 'Tab', '_func'],
        ['Й', 'KeyQ'],
        ['Ц', 'KeyW'],
        ['У', 'KeyE'],
        ['К', 'KeyR'],
        ['Е', 'KeyT'],
        ['Н', 'KeyY'],
        ['Г', 'KeyU'],
        ['Ш', 'KeyI'],
        ['Щ', 'KeyO'],
        ['З', 'KeyP'],
        ['Х', 'BracketLeft'],
        ['Ъ', 'BracketRight'],
        ['| \\', 'Backslash'],
        ['Del', 'Delete'],
        //~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
        ['Caps\tLock', 'CapsLock', '_func'],
        ['Ф', 'KeyA'],
        ['Ы', 'KeyS'],
        ['В', 'KeyD'],
        ['А', 'KeyF'],
        ['П', 'KeyG'],
        ['Р', 'KeyH'],
        ['О', 'KeyJ'],
        ['Л', 'KeyK'],
        ['Д', 'KeyL'],
        ['Ж', 'Semicolon'],
        ['Э', 'Quote'],
        ['Enter', 'Enter', '_func'],
        //~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
        ['Shift', 'ShiftLeft', '_func'],
        ['\\', 'Backslash'],
        ['Я', 'KeyZ'],
        ['Ч', 'KeyX'],
        ['С', 'KeyC'],
        ['М', 'KeyV'],
        ['И', 'KeyB'],
        ['Т', 'KeyN'],
        ['Ь', 'KeyM'],
        ['Б', 'Comma'],
        ['Ю', 'Period'],
        [', .', 'Slash'],
        ['', 'ArrowUp', '_func'],
        ['Shift', 'ShiftRight', '_func'],
        //~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
        ['Ctrl', 'ControlLeft', '_func'],
        ['Win', 'MetaLeft', '_func'],
        ['Alt', 'AltLeft', '_func'],
        ['', 'Space'],
        ['Alt', 'AltRight', '_func'],
        ['Ctrl', 'ControlRight', '_func'],
        ['', 'ArrowLeft', '_func'],
        ['', 'ArrowDown', '_func'],
        ['', 'ArrowRight', '_func'],
    ]
};